=== mohbadar/upos/src/test/resources/iso8583.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://s.rockagen.com/schema/iso8583/define"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://s.rockagen.com/schema/iso8583/define"
	elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" />

	<xs:annotation>
		<xs:documentation>
		<![CDATA[
			Defines the elements used in the upos  support for  iso8583 message parse.
		]]>
		</xs:documentation>
	</xs:annotation>

	<xs:element name="define">
		<xs:complexType>
			<xs:all>
				<xs:element name="headers" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="header" minOccurs="0" maxOccurs="9999"
								type="hdtype">
								<xs:annotation>
									<xs:documentation>
		<![CDATA[
			Defines the elements used for iso8583 message header.
		]]>
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="templates" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="template" minOccurs="0" maxOccurs="9999"
								type="tltype">
								<xs:annotation>
									<xs:documentation>
		<![CDATA[
			Defines the elements used for iso8583 message template.
		]]>
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="parsers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>

							<xs:element name="parser" minOccurs="0" maxOccurs="9999"
								type="pstype">
								<xs:annotation>
									<xs:documentation>
		<![CDATA[
			Defines the elements used for iso8583 message parser
		]]>
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="hdtype">

		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attributeGroup ref="mtype" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>


	<xs:complexType name="tltype">

		<xs:complexContent>
			<xs:extension base="fieldtype">
				<xs:attributeGroup ref="mtype" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>



	<xs:complexType name="pstype">
		<xs:complexContent>
			<xs:extension base="fieldtype">
				<xs:attributeGroup ref="mtype" />
			</xs:extension>
		</xs:complexContent>

	</xs:complexType>

	<xs:attributeGroup name="mtype">
		<xs:attribute name="type" use="required">
			<xs:annotation>
				<xs:documentation>
		<![CDATA[
			Defines the elements used for iso8583 message transaction type.
			example: 0100,0200...
		]]>
				</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[0-9]{4}" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>


	<xs:complexType name="fieldtype">
		<xs:sequence>
			<xs:element name="field" minOccurs="0" maxOccurs="128">
				<xs:annotation>
					<xs:documentation>
		<![CDATA[
			Defines the elements used for iso8583 message field.
			for example:
			# PROCESSING CODE
			<field num="3" type="NUMERIC" length="6" />
		]]>
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="num" use="required">
								<xs:annotation>
									<xs:documentation>
		<![CDATA[
			Defines the elements used for iso8583 message field index.
			example: 
			2 -> PRIMARY ACCOUNT NUMBER
			3 -> PROCESSING CODE
			4 -> AMOUNT, TRANSACTION
			
		]]>
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0" />
										<xs:maxInclusive value="128" />
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="type" use="required">
								<xs:annotation>
									<xs:documentation>
		<![CDATA[
			Defines the elements used for iso8583 message field type.
		]]>
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="NUMERIC" />
										<xs:enumeration value="ALPHA" />
										<xs:enumeration value="LLVAR" />
										<xs:enumeration value="LLLVAR" />
										<xs:enumeration value="DATE10" />
										<xs:enumeration value="DATE4_YM" />
										<xs:enumeration value="DATE4_MD" />
										<xs:enumeration value="TIME" />
										<xs:enumeration value="AMOUNT" />
										<xs:enumeration value="BINARY" />
									</xs:restriction>

								</xs:simpleType>
							</xs:attribute>


							<xs:attribute name="length" use="optional">

								<xs:annotation>
									<xs:documentation>
		<![CDATA[
			Defines the elements used for iso8583 message field length,this attribute is optional.
		]]>
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0" />
										<xs:maxInclusive value="999" />
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>

						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


</xs:schema>

=== mohbadar/upos/src/test/resources/iso8583.xml
<?xml version="1.0" encoding="UTF-8"?>
<define
xmlns="http://s.rockagen.com/schema/iso8583/define"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://upos.rockagen.com/schema/iso8583/define iso8583.xsd">

	<!-- Headers -->
	<headers>
		<header type="0210">abc</header>
		<header type="0110"/>
		<header type="0100">abc</header>
	</headers>
	<!-- Templates -->
	<templates>
		<template type="0210">
		</template>
		<template type="0820">
			<field num="33" type="LLVAR" length="9">ABC123456</field>
		</template>
		<template type="0110">
		</template>
	</templates>

	<!-- Parsers -->

	<parsers>
		<!-- The server, this to read the request -->
		<parser type="0200">
			<field num="2" type="LLVAR" />
			<field num="3" type="NUMERIC" length="6" />
			<field num="4" type="AMOUNT" />
			<field num="7" type="DATE10" />
			<field num="11" type="NUMERIC" length="6" />
			<field num="12" type="TIME" />
			<field num="13" type="DATE4_MD" />
			<field num="15" type="DATE4_MD" />
			<field num="18" type="NUMERIC" length="4" />
			<field num="22" type="NUMERIC" length="3" />
			<field num="25" type="NUMERIC" length="2" />
			<field num="32" type="LLVAR" />
			<field num="33" type="LLVAR" />
			<field num="37" type="ALPHA" length="12" />
			<field num="39" type="ALPHA" length="2" />
			<field num="41" type="ALPHA" length="8" />
			<field num="42" type="ALPHA" length="15" />
			<field num="48" type="LLLVAR" />
			<field num="49" type="NUMERIC" length="3" />
			<!-- bytes -->
			<field num="52" type="BINARY" length="8" />
			<field num="53" type="NUMERIC" length="16" />
			<field num="54" type="LLLVAR" />
			<field num="59" type="LLLVAR" />
			<field num="60" type="LLLVAR" />
			<field num="63" type="LLLVAR" />
			<field num="100" type="LLVAR" />
			<field num="103" type="LLVAR" />
			<!-- bytes -->
			<field num="128" type="BINARY" length="8" />
		</parser>

		<!-- The server, this to read the request -->
		<parser type="0100">
			<field num="3" type="NUMERIC" length="6" />
			<field num="7" type="DATE10" />
			<field num="11" type="NUMERIC" length="6" />
			<field num="12" type="TIME" />
			<field num="13" type="DATE4_MD" />
			<field num="15" type="DATE4_MD" />
			<field num="18" type="NUMERIC" length="4" />
			<field num="22" type="NUMERIC" length="3" />
			<field num="25" type="NUMERIC" length="2" />
			<field num="32" type="LLVAR" />
			<field num="33" type="LLVAR" />
			<field num="37" type="ALPHA" length="12" />
			<field num="39" type="ALPHA" length="2" />
			<field num="41" type="ALPHA" length="8" />
			<field num="42" type="ALPHA" length="15" />
			<field num="48" type="LLLVAR" />
			<field num="49" type="NUMERIC" length="3" />
			<!-- bytes -->
			<field num="52" type="BINARY" length="8" />
			<field num="53" type="NUMERIC" length="16" />
			<field num="54" type="LLLVAR" />
			<field num="59" type="LLLVAR" />
			<field num="60" type="LLLVAR" />
			<field num="61" type="LLLVAR" />
			<field num="100" type="LLVAR" />
			<field num="103" type="LLVAR" />
			<!-- bytes -->
			<field num="128" type="BINARY" length="8" />
		</parser>
		
		
			<!-- The server, this to read the request -->
		<parser type="0800">
			<field num="7" type="DATE10" />
			<field num="11" type="NUMERIC" length="6" />
			<field num="33" type="LLVAR" length="11"/>
			<field num="39" type="ALPHA" length="2" />
			<!-- If first digit is 1 means that PIK,2 means MAK -->
			<field num="53" type="NUMERIC" length="16" />
			<field num="70" type="NUMERIC" length="3" />
			<field num="96" type="BINARY" length="8" />
			<!-- bytes -->
			<field num="128" type="BINARY" length="8" />
		</parser>
		
			<!-- The server, this to response the request -->
		<parser type="0810">
			<field num="7" type="DATE10" />
			<field num="11" type="NUMERIC" length="6" />
			<field num="33" type="LLVAR" length="11"/>
			<field num="39" type="ALPHA" length="2" />
			<!-- If first digit is 1 means that PIK,2 means MAK -->
			<field num="53" type="NUMERIC" length="16" />
			<field num="70" type="NUMERIC" length="3" />
			<field num="96" type="BINARY" length="8" />
			<!-- bytes -->
			<field num="128" type="BINARY" length="8" />
		</parser>
		
			<!-- The server, this to read the request -->
		<parser type="0820">
			<field num="7" type="DATE10" />
			<field num="11" type="NUMERIC" length="6" />
			<field num="33" type="LLVAR" length="11"/>
			<field num="39" type="ALPHA" length="2" />
			<!-- If first digit is 1 means that PIK,2 means MAK -->
			<field num="53" type="NUMERIC" length="16" />
			<field num="70" type="NUMERIC" length="3" />
		</parser>
		
			<!-- The server, this to response the request -->
		<parser type="0830">
			<field num="7" type="DATE10" />
			<field num="11" type="NUMERIC" length="6" />
			<field num="33" type="LLVAR" length="11"/>
			<field num="39" type="ALPHA" length="2" />
			<!-- If first digit is 1 means that PIK,2 means MAK -->
			<field num="53" type="NUMERIC" length="16" />
			<field num="70" type="NUMERIC" length="3" />
		</parser>


		<!-- The server, this to write the response -->
		<parser type="0210">
			<field num="2" type="LLVAR" length="19" />
			<field num="3" type="NUMERIC" length="6" />
			<field num="4" type="AMOUNT" />
			<field num="7" type="DATE10" />
			<field num="11" type="NUMERIC" length="6" />
			<field num="12" type="TIME" />
			<field num="13" type="DATE4_MD" />
			<field num="15" type="DATE4_MD" />
			<field num="18" type="NUMERIC" length="4" />
			<field num="22" type="NUMERIC" length="3" />
			<field num="25" type="NUMERIC" length="2" />
			<field num="32" type="LLVAR" />
			<field num="33" type="LLVAR" />
			<field num="37" type="ALPHA" length="12" />
			<field num="39" type="ALPHA" length="2" />
			<field num="41" type="ALPHA" length="8" />
			<field num="42" type="ALPHA" length="15" />
			<field num="48" type="LLLVAR" />
			<field num="49" type="ALPHA" length="3" />
			<!-- bytes -->
			<field num="52" type="BINARY" length="8" />
			<field num="53" type="NUMERIC" length="16" />
			<field num="54" type="LLLVAR" />
			<field num="59" type="LLLVAR" />
			<field num="60" type="LLLVAR" />
			<field num="63" type="LLLVAR" />
			<field num="100" type="LLVAR" />
			<field num="103" type="LLVAR" />
			<!-- bytes -->
			<field num="128" type="BINARY" length="8" />
		</parser>
		
		
		<!-- The server, this to read the request -->
		<parser type="0110">
			<field num="3" type="NUMERIC" length="6" />
			<field num="7" type="DATE10" />
			<field num="11" type="NUMERIC" length="6" />
			<field num="12" type="TIME" />
			<field num="13" type="DATE4_MD" />
			<field num="15" type="DATE4_MD" />
			<field num="18" type="NUMERIC" length="4" />
			<field num="22" type="NUMERIC" length="3" />
			<field num="25" type="NUMERIC" length="2" />
			<field num="32" type="LLVAR" />
			<field num="33" type="LLVAR" />
			<field num="37" type="ALPHA" length="12" />
			<field num="39" type="ALPHA" length="2" />
			<field num="41" type="ALPHA" length="8" />
			<field num="42" type="ALPHA" length="15" />
			<field num="48" type="LLLVAR" />
			<field num="49" type="NUMERIC" length="3" />
			<!-- bytes -->
			<field num="52" type="BINARY" length="8" />
			<field num="53" type="NUMERIC" length="16" />
			<field num="54" type="LLLVAR" />
			<field num="59" type="LLLVAR" />
			<field num="60" type="LLLVAR" />
			<field num="61" type="LLLVAR" />
			<field num="100" type="LLVAR" />
			<field num="103" type="LLVAR" />
			<!-- bytes -->
			<field num="128" type="BINARY" length="8" />
		</parser>
	</parsers>
</define>
